# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Hajime Taira <htaira@redhat.com>, 2012
# hyuugabaru <hyu_gabaru@yahoo.co.jp>, 2009
# Kiyoto Hashida <khashida@redhat.com>, 2008-2012
# Kiyoto Hashida <khashida@redhat.com>, 2006, 2007
# noriko <noriko@fedoraproject.org>, 2013
# noriko <noriko@fedoraproject.org>, 2012
# Noriko Mizumoto <noriko@redhat.com>, 2006, 2008
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2012-2013
# Kenzo Moriguchi <kmoriguc@redhat.com>, 2016. #zanata
# Noriko Mizumoto <noriko@redhat.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-04-15 20:42+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-03-14 09:56-0400\n"
"Last-Translator: Kenzo Moriguchi <kmoriguc@redhat.com>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/fedora/language/"
"ja/)\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Zanata 3.9.1\n"

#: ../src/allow_anon_write.py:27
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.\n"
"    "
msgstr "\n"
"SELinux ポリシーにより httpd スクリプトのパブリックディレクトリへの書き込むが\n"
"阻止されています。\n"
"     "

#: ../src/allow_anon_write.py:32
msgid ""
"\n"
"    SELinux policy is preventing an httpd script from writing to a public\n"
"    directory.  If httpd is not setup to write to public directories, this\n"
"    could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux ポリシーにより httpd スクリプトのパブリックディレクトリへの書き込みが\n"
"阻止されています。 httpd でパブリックディレクトリへの書き込み設定を行なって\n"
"いない場合、 セキュリティ侵害が行なわれた可能性があります。\n"
"    "

#: ../src/allow_anon_write.py:38
msgid ""
"\n"
"    If httpd scripts should be allowed to write to public directories you "
"need to turn on the $BOOLEAN boolean and change the file context of the "
"public directory to public_content_rw_t.  Read the httpd_selinux\n"
"    man page for further information:\n"
"    \"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t <path>\"\n"
"    You must also change the default file context labeling files on the "
"system in order to preserve public directory labeling even on a full relabel."
"  \"semanage fcontext -a -t public_content_rw_t <path>\"\n"
"    "
msgstr ""
"\n"
"httpd スクリプトによるパブリックディレクトリへの書き込みを許可する場合、 $BOOLEAN boolean "
"をオンにしてパブリックディレクトリのファイルコンテキストを public_content_rw_t に変更する必要があります。 詳細については "
"httpd_selinux の man ページをご覧ください:\n"
"\"setsebool -P $BOOLEAN=1; chcon -t public_content_rw_t<path>\"\n"
"また、 完全な再ラベル付けを行なった後もパブリックディレクトリのラベルを維持させたい場合は、 "
"システム上のデフォルトのファイルコンテキストラベル設定ファイルも変更する必要があります。 \"semanage fcontext -a -t "
"public_content_rw_t <path>\""

#: ../src/allow_anon_write.py:44
msgid ""
"you want to allow $SOURCE_PATH to be able to write to shared public content"
msgstr "$SOURCE_PATH による共有の公開コンテンツへの書き込みを許可します"

#: ../src/allow_anon_write.py:45
msgid ""
"you need to change the label on $TARGET_PATH to public_content_rw_t, and "
"potentially turn on the allow_httpd_sys_script_anon_write boolean."
msgstr ""
"$TARGET_PATH のラベルを public_content_rw_t に変更する必要があります。 また、 "
"allow_httpd_sys_script_anon_write boolean を有効にする必要があるかもしれません。"

#: ../src/allow_execheap.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from changing the access\n"
"    protection of memory on the heap.\n"
"    "
msgstr ""
"\n"
"     SELinux は $SOURCE_PATH が ヒープのメモリーへのアクセス保護を\n"
"     変更することを阻止しています。\n"
"     "

#: ../src/allow_execheap.py:32
msgid ""
"\n"
"    The $SOURCE application attempted to change the access protection of "
"memory on\n"
"    the heap (e.g., allocated using malloc).  This is a potential security\n"
"    problem.  Applications should not be doing this. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not "
"work and\n"
"    you need it to work, you can configure SELinux temporarily to allow\n"
"    this access until the application is fixed. Please file a bug\n"
"    report against this package.\n"
"    "
msgstr ""
"\n"
"    $SOURCE アプリケーションがヒープのメモリー (例えば malloc を使った割当て)\n"
"    のアクセス保護の変更を試行しました。セキュリティー上の問題となる可能性が\n"
"    あります。アプリケーションはこのような動作を行うべきではありません。\n"
"    アプリケーションは誤って記述されることがあり、 このパーミッションを要求\n"
"    することがあります。\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    のウェブページにはこの要求の削除方法が記載されています。 $SOURCE が動作しなくて\n"
"    動作させる必要がある場合、 アプリケーションが修正されるまでの間、 \n"
"    SELinux を設定して一時的にこのアクセスを許可することができます。 このパッケージ\n"
"    に関するバグレポートを提出してください。\n"
"    "

#: ../src/allow_execheap.py:44
msgid ""
"\n"
"    If you want $SOURCE to continue, you must turn on the\n"
"    $BOOLEAN boolean.  Note: This boolean will affect all applications\n"
"    on the system.\n"
"    "
msgstr ""
"\n"
"    $SOURCE を継続したい場合は、$BOOLEAN boolean をオンにする必要があり\n"
"    ます。 注記: この boolean はシステム上の全てのアプリケーションに影響\n"
"    します。\n"
"    "

#: ../src/allow_execheap.py:50
msgid ""
"you do not think $SOURCE_PATH should need to map heap memory that is both "
"writable and executable."
msgstr "$SOURCE_PATH に書き込みと実行の両方が可能となるヒープメモリーのマッピングを行なう必要があるとは思えません。"

#: ../src/allow_execheap.py:51
msgid "you need to report a bug. This is a potentially dangerous access."
msgstr "バグをレポートする必要があります。これは危険なアクセスです。"

#: ../src/allow_execheap.py:52 ../src/allow_execstack.py:84
#: ../src/kernel_modules.py:46 ../src/mmap_zero.py:48
#: ../src/selinuxpolicy.py:46 ../src/setenforce.py:29 ../src/setenforce.py:50
#: ../src/sys_module.py:30 ../src/sys_module.py:48
msgid "Contact your security administrator and report this issue."
msgstr "セキュリティ管理者にコンタクトし、この問題を報告してください。"

#: ../src/allow_execmod.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from loading $TARGET_PATH which "
"requires text relocation.\n"
"    "
msgstr ""
"\n"
"    SELinux はテキスト再配置を要求する $TARGET_PATH を $SOURCE_PATH がロードすることを阻止しています。\n"
"    "

#: ../src/allow_execmod.py:33
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries do not need this permission. Libraries are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  You can configure\n"
"    SELinux temporarily to allow $TARGET_PATH to use relocation as a\n"
"    workaround, until the library is fixed. Please file a\n"
"bug report.\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:45
msgid ""
"\n"
"    The $SOURCE application attempted to load $TARGET_PATH which\n"
"    requires text relocation.  This is a potential security problem.\n"
"    Most libraries should not need this permission.   The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">\n"
"    SELinux Memory Protection Tests</a>\n"
"    web page explains this check.  This tool examined the library and it "
"looks\n"
"    like it was built correctly. So setroubleshoot can not determine if this\n"
"    application is compromized or not.  This could be a serious issue. Your\n"
"    system may very well be compromised.\n"
"\n"
"    Contact your security administrator and report this issue.\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execmod.py:62
msgid ""
"\n"
"    If you trust $TARGET_PATH to run correctly, you can change the\n"
"    file context to textrel_shlib_t. \"chcon -t textrel_shlib_t\n"
"    '$TARGET_PATH'\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"textrel_shlib_t '$FIX_TARGET_PATH'\"\n"
"\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:53
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from making the program stack "
"executable.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH がプログラムスタックを実行可能にすることを阻止しています。\n"
"    "

#: ../src/allow_execstack.py:57
msgid ""
"\n"
"    The $SOURCE application attempted to make its stack\n"
"    executable.  This is a potential security problem.  This should\n"
"    never ever be necessary. Stack memory is not executable on most\n"
"    OSes these days and this will not change. Executable stack memory\n"
"    is one of the biggest security problems. An execstack error might\n"
"    in fact be most likely raised by malicious code. Applications are\n"
"    sometimes coded incorrectly and request this permission.  The\n"
"    <a href=\"http://people.redhat.com/drepper/selinux-mem.html\">SELinux "
"Memory Protection Tests</a>\n"
"    web page explains how to remove this requirement.  If $SOURCE does not\n"
"    work and you need it to work, you can configure SELinux\n"
"    temporarily to allow this access until the application is fixed. Please\n"
"file a bug report.\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:72
msgid ""
"\n"
"    Sometimes a library is accidentally marked with the execstack flag,\n"
"    if you find a library with this flag you can clear it with the\n"
"    execstack -c LIBRARY_PATH.  Then retry your application.  If the\n"
"    app continues to not work, you can turn the flag back on with\n"
"    execstack -s LIBRARY_PATH.\n"
"    "
msgstr ""

#: ../src/allow_execstack.py:82
msgid ""
"you do not think $SOURCE_PATH should need to map stack memory that is both "
"writable and executable."
msgstr "$SOURCE_PATH に書き込みと実行の両方が可能となるスタックメモリーのマッピングを行なう必要があるとは思えません。"

#: ../src/allow_execstack.py:83
msgid "you need to report a bug. \n"
"This is a potentially dangerous access."
msgstr "バグをレポートする必要があります。\n"
"これは危険なアクセスです。"

#: ../src/allow_execstack.py:92
#, python-format
msgid "you believe that \n"
"%s\n"
"should not require execstack"
msgstr "%s は execstack を必要としないと信じています"

#: ../src/allow_execstack.py:101
#, python-format
msgid ""
"you should clear the execstack flag and see if $SOURCE_PATH works correctly.\n"
"Report this as a bug on %s.\n"
"You can clear the exestack flag by executing:"
msgstr ""
"execstack フラグをクリアして $SOURCE_PATH が正常に機能していることを確認する必要があります。\n"
"これは %s のバグとして報告します。\n"
"あなたは以下の実行による execstack フラグをクリアすることができます。"

#: ../src/allow_execstack.py:111
#, python-format
msgid "execstack -c %s"
msgstr "execstack -c %s"

#: ../src/allow_ftpd_use_cifs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"     SELinux は ftp デーモンが $ACCESS から CIFS ファイルシステム上に保存されているファイルへのアクセスを阻止しました。\n"
"      "

#: ../src/allow_ftpd_use_cifs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a CIFS "
"filesystem.\n"
"    CIFS (Comment Internet File System) is a network filesystem similar to\n"
"    SMB (<a href=\"http://www.microsoft.com/mind/1196/cifs.asp\">http://www."
"microsoft.com/mind/1196/cifs.asp</a>)\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As CIFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a CIFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/allow_ftpd_use_cifs.py:46
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "
msgstr ""
"\n"
"    \"$BOOLEAN\" boolean を 「true」に変更するとこのアクセスを許可します:\n"
"    \"setsebool -P $BOOLEAN=1.\"\n"
"    "

#: ../src/allow_ftpd_use_cifs.py:53
msgid ""
" Changing the \"$BOOLEAN\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on CIFS filesystems.  "
msgstr ""
"\"$BOOLEAN\" 及び \"$WRITE_BOOLEAN\" の boolean を true に変更すると、 \n"
"このアクセスが許可されます:\n"
"\"setsebool -P $BOOLEAN=1 $WRITE_BOOLEAN=1\"\n"
"警告: \"$WRITE_BOOLEAN\" の boolean を true に設定すると、 CIFS \n"
"ファイルシステム上のファイルやディレクトリへの書き込みに加えて、 \n"
"すべての公開コンテンツ (タイプが public_content_t のファイルと\n"
"ディレクトリ) への書き込みも ftp デーモンに許可することになります。"

#: ../src/allow_ftpd_use_cifs.py:62
msgid "you want to allow ftpd to write to cifs file systems"
msgstr "ftpdが、cifs ファイルシステムに書込むことを、許可したい"

#: ../src/allow_ftpd_use_cifs.py:63 ../src/allow_ftpd_use_nfs.py:65
msgid "you must tell SELinux about this"
msgstr "これについては、SELinux に設定をしなければいけません"

#: ../src/allow_ftpd_use_nfs.py:29
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    "
msgstr ""
"\n"
"     SELinux は ftp デーモンが $ACCESS から NFS ファイルシステム上に保存されているファイルへのアクセスを阻止しました。\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:33
msgid ""
"\n"
"    SELinux prevented the ftp daemon from $ACCESS files stored on a NFS "
"filesystem.\n"
"    NFS (Network Filesystem) is a network filesystem commonly used on Unix / "
"Linux\n"
"    systems.\n"
"\n"
"    The ftp daemon attempted to read one or more files or directories from\n"
"    a mounted filesystem of this type.  As NFS filesystems do not support\n"
"    fine-grained SELinux labeling, all files and directories in the\n"
"    filesystem will have the same security context.\n"
"\n"
"    If you have not configured the ftp daemon to read files from a NFS "
"filesystem\n"
"    this access attempt could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/allow_ftpd_use_nfs.py:47
msgid ""
"\n"
"    Changing the \"allow_ftpd_use_nfs\" boolean to true will allow this "
"access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "
msgstr ""
"\n"
"      \"allow_ftpd_use_nfs\" boolean を「true」に変更するとこのアクセスを 許可します:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1.\"\n"
"    "

#: ../src/allow_ftpd_use_nfs.py:54
msgid ""
" Changing the \"allow_ftpd_use_nfs\" and\n"
"    \"$WRITE_BOOLEAN\" booleans to true will allow this access:\n"
"    \"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\".\n"
"    warning: setting the \"$WRITE_BOOLEAN\" boolean to true will\n"
"    allow the ftp daemon to write to all public content (files and\n"
"    directories with type public_content_t) in addition to writing to\n"
"    files and directories on NFS filesystems.  "
msgstr ""
"\"allow_ftpd_use_nfs\" と \"$WRITE_BOOLEAN\" の boolean を\n"
"true に変更すると、 このアクセスが許可されます:\n"
"\"setsebool -P allow_ftpd_use_nfs=1 $WRITE_BOOLEAN=1\"\n"
"警告: \"$WRITE_BOOLEAN\" の boolean を true に設定すると、 \n"
"NFS ファイルシステム上のファイルやディレクトリへの\n"
"書き込みに加えて、 すべての公開コンテンツ (タイプが \n"
"public_content_t のファイルとディレクトリ) への書き込みも \n"
"ftp デーモンに許可することになります。"

#: ../src/allow_ftpd_use_nfs.py:64
msgid "you want to allow ftpd to write to nfs file systems"
msgstr "ftpd が、nfs ファイルシステムに書込むことを、許可したい"

#: ../src/associate.py:32 ../src/openvpn.py:31 ../src/public_content.py:27
#: ../src/qemu_blk_image.py:27 ../src/qemu_file_image.py:27
#: ../src/restorecon.py:42 ../src/restorecon_source.py:33
#: ../src/rsync_data.py:27 ../src/sshd_root.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH による $TARGET_PATH への \"$ACCESS\" アクセスを阻止しています。\n"
"    "

#: ../src/associate.py:37
#, python-format
msgid ""
"\n"
"You tried to place a type on a %s that is not a file type.  This is not "
"allowed, you must assigne a file type.  You can list all file types using "
"the seinfo command.\n"
"\n"
"seinfo -afile_type -x\n"
"\n"
"    "
msgstr ""
"\n"
" %s 上にファイルタイプではない１つのタイプの配置を試みました。これは許可されていないため、ファイルタイプを指定する必要があります。次の seinfo "
"コマンドを使用すると、全てのファイルタイプを一覧表示することが出来ます。⏎ ⏎ seinfo -afile_type -x⏎ ⏎ "

#: ../src/associate.py:44
#, python-format
msgid ""
"you want to change the label of $TARGET_PATH to %s, you are not allowed to "
"since it is not a valid file type."
msgstr "$TARGET_PATH のラベルを %s に変更したくても、それは有効なファイルタイプではないため、許可されません。"

#: ../src/associate.py:49
msgid "you must pick a valid file label."
msgstr "有効なファイルラベルを選択する必要があります。"

#: ../src/automount_exec_config.py:27
msgid ""
"\n"
"    SELinux is preventing the $SOURCE_PATH from executing potentially "
"mislabeled files $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH による、誤ったラベル付けの可能性のあるファイル $TARGET_PATH の使用を阻止しています。\n"
"    "

#: ../src/automount_exec_config.py:31
msgid ""
"\n"
"    SELinux has denied the $SOURCE_PATH from executing potentially\n"
"    mislabeled files $TARGET_PATH.  Automounter can be setup to execute\n"
"    configuration files. If $TARGET_PATH is an automount executable\n"
"    configuration file it needs to have a file label of bin_t.\n"
"    If automounter is trying to execute something that it is not supposed "
"to, this could indicate an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE_PATH が間違ったラベルを持つ可能性のあるファイル\n"
"      $TARGET_PATH を実行するのを拒否しました。自動マウンタは設定ファイルを\n"
"      実行するようにセット出来ます。 $TARGET_PATH が自動マウント実行可能な \n"
"     設定ファイルである場合、bin_t のファイルラベルを持つ必要があります。\n"
"      自動マウンタが想定されていない何かを実行しようとしている場合、\n"
"     これは不正侵入をを示唆している可能性があります。\n"
"     "

#: ../src/automount_exec_config.py:39
msgid ""
"\n"
"    If you want to change the file context of $TARGET_PATH so that the "
"automounter can execute it you can execute \"chcon -t bin_t $TARGET_PATH\".  "
"If you want this to survive a relabel, you need to permanently change the "
"file context: execute  \"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\".\n"
"    "
msgstr ""
"\n"
"自動マウンタで実行できるよう $TARGET_PATH のファイルコンテキストを変更する場合は、 \"chcon -t bin_t "
"$TARGET_PATH\" を実行します。 再ラベル後もこの変更を維持させる場合は、 ファイルコンテキストを永久に変更する必要があります。 "
"\"semanage fcontext -a -t bin_t '$FIX_TARGET_PATH'\" を実行します。\n"
"    "

#: ../src/bind_ports.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from binding to port $PORT_NUMBER.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH によるポート $PORT_NUMBER へのバインドを阻止しています。\n"
"    "

#: ../src/bind_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE from binding to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to listen on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can bind to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to bind to $PORT_NUMBER, this could signal an intrusion attempt.\n"
"    "
msgstr ""

#: ../src/bind_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to bind to port $PORT_NUMBER, you can "
"execute \n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"where PORT_TYPE is one of the following: %s.\n"
"\n"
"    \n"
"\n"
"If this system is running as an NIS Client, turning on the allow_ypbind "
"boolean may fix the problem.  setsebool -P allow_ypbind=1.\n"
"    "
msgstr ""
"\n"
"     $SOURCE がポート $PORT_NUMBER にバインドできるようにしたい場合、以下コマンドを実行します。\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    \n"
"ここで PORT_TYPE は下のいずれかです: %s.\n"
"\n"
"    \n"
"\n"
"使用システムが NIS クライアントとして稼働している場合、 allow_ypbind boolean "
"をオンにすると問題を解決するかも知れません。setsebool -P allow_ypbind=1\n"
"    "

#: ../src/bind_ports.py:53 ../src/connect_ports.py:51
#, python-format
msgid ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"    where PORT_TYPE is one of the following: %s."
msgstr ""
"# semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"　　ここで、PORT_TYPE は 以下の１つとなります: %s    "

#: ../src/bind_ports.py:56 ../src/connect_ports.py:54
#, python-format
msgid "# semanage port -a -t %s -p %s $PORT_NUMBER"
msgstr "# semanage port -a -t %s -p %s $PORT_NUMBER"

#: ../src/catchall_boolean.py:32
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access on $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は  $TARGET_PATH への $SOURCE_PATH による \"$ACCESS\" アクセスを阻止しています。\n"
"    "

#: ../src/catchall_boolean.py:36
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. The current boolean\n"
"    settings do not allow this access.  If you have not setup $SOURCE to\n"
"    require this access this may signal an intrusion attempt. If you do "
"intend\n"
"    this access you need to change the booleans on this system to allow\n"
"    the access.\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:45
msgid ""
"\n"
"    Confined processes can be configured to run requiring different access, "
"SELinux provides booleans to allow you to turn on/off\n"
"    access as needed.\n"
"\n"
"    "
msgstr ""

#: ../src/catchall_boolean.py:62
#, python-format
msgid "you want to %s"
msgstr "%s がしたい"

#: ../src/catchall_boolean.py:65
#, python-format
msgid "setsebool -P %s %s"
msgstr "setsebool -P %s %s"

#: ../src/catchall_boolean.py:68
#, python-format
msgid "You must tell SELinux about this by enabling the '%s' boolean.\n"
msgstr "'%s' boolean を有効にすることにより、 これを SELinux に伝える必要があります。\n"

#: ../src/catchall_boolean.py:71
#, python-format
msgid "You can read '%s' man page for more details."
msgstr "詳細情報については、'%s' man ページをご覧下さい。"

#: ../src/catchall_labels.py:28
#, python-format
msgid ""
"\n"
"    SELinux has denied the $SOURCE access to potentially\n"
"    mislabeled files $TARGET_PATH.  This means that SELinux will not\n"
"    allow httpd to use these files. If httpd should be allowed this access "
"to these files you should change the file context to one of the following "
"types, %s.\n"
"    Many third party apps install html files\n"
"    in directories that SELinux policy cannot predict.  These directories\n"
"    have to be labeled with a file context which httpd can access.\n"
"    "
msgstr ""
"\n"
"SELinux により誤ったラベル付けの可能性のある $TARGET_PATH ファイル\n"
"への $SOURCE のアクセスが拒否されています。 これは、 SELinux では httpd \n"
"によるこれらのファイルの使用が許可されないということになります。 \n"
"httpd にこうしたファイルへの同様の アクセスを許可する場合は、 \n"
"ファイルコンテキストを次のいずれかのタイプに変更する必要があります、 %s。\n"
"多くのサードパーティーのアプリケーションでは、 SELinux ポリシーでは\n"
"予期できないディレクトリ内に html ファイルがインストールされます。\n"
"これらのディレクトリには httpd によるアクセスが可能なファイルコンテキスト\n"
"でラベル付けを行なう必要があります。"

#: ../src/catchall_labels.py:37
msgid "You need to change the label on $FIX_TARGET_PATH"
msgstr "$FIX_TARGET_PATH のラベルを変更する必要があります"

#: ../src/catchall_labels.py:40
#, python-format
msgid ""
"# semanage fcontext -a -t FILE_TYPE '$FIX_TARGET_PATH'\n"
"where FILE_TYPE is one of the following: %s.\n"
"Then execute:\n"
"restorecon -v '$FIX_TARGET_PATH'\n"
msgstr ""

#: ../src/catchall.py:29 ../src/chrome.py:29 ../src/mozplugger.py:29
#: ../src/mozplugger_remove.py:29
msgid "SELinux is preventing $SOURCE_PATH \"$ACCESS\" access."
msgstr "SELinux は $SOURCE_PATH による \"$ACCESS\" アクセスを阻止しています。    "

#: ../src/catchall.py:31
msgid ""
"\n"
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"\n"
"    "
msgstr ""
"\n"
"\n"
"    SELinux は $SOURCE により要求されたアクセスを拒否しました。 \n"
"    このアクセスは $SOURCE に必要であると想定されないため不正侵入\n"
"    の試行を示している可能性があります。 また、 アプリケーションの特定\n"
"    バージョンまたは設定が追加アクセス要求の原因となっている可能性\n"
"    もあります。\n"
"\n"
"    "

#: ../src/catchall.py:41
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"\n"
"    Please file a bug report.\n"
"    "
msgstr ""
"\n"
"    ローカルポリシーモジュールを生成して、このアクセスを許可するように\n"
"    できます：<a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a> をご覧下さい。\n"
"\n"
"    バグレポートを提出してください。\n"
"    "

#: ../src/catchall.py:50
msgid ""
"you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on "
"processes labeled $TARGET_TYPE by default."
msgstr ""
"$SOURCE_BASE_PATH に、 $TARGET_TYPE にラベルされている $ACCESS アクセスがデフォルトで許可されるべきです。   "

#: ../src/catchall.py:52
msgid ""
"you believe that $SOURCE_BASE_PATH should have the $ACCESS capability by "
"default."
msgstr "$SOURCE_BASE_PATH には $ACCESS 機能をデフォルトで持たせるべきだと思います。"

#: ../src/catchall.py:53
msgid ""
"you believe that $SOURCE_BASE_PATH should be allowed $ACCESS access on the "
"$TARGET_BASE_PATH $TARGET_CLASS by default."
msgstr ""
"$SOURCE_BASE_PATH に、 $TARGET_BASE_PATH $TARGET_CLASS の $ACCESS "
"アクセスがデフォルトで許可されるべきです。   "

#: ../src/catchall.py:55
msgid ""
"You should report this as a bug.\n"
"You can generate a local policy module to allow this access."
msgstr "バグとして報告してください。 \n"
"ローカルのポリシーモジュールを生成すると、\n"
" このアクセスを許可することができます。"

#: ../src/catchall.py:56
msgid ""
"Allow this access for now by executing:\n"
"# ausearch -c $SOURCE --raw | audit2allow -M mypol\n"
"# semodule -i mypol.pp"
msgstr ""

#: ../src/connect_ports.py:27 ../src/sandbox_connect.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from connecting to port $PORT_NUMBER.\n"
"    "
msgstr "\n"
"    SELinux は $SOURCE_PATH によるポート $PORT_NUMBER への接続を 阻止しています。\n"
"    "

#: ../src/connect_ports.py:31
#, python-format
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER which does not have an SELinux type associated with it.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, use the "
"<i>semanage</i> command to assign $PORT_NUMBER to a port type that "
"$SOURCE_TYPE can connect to (%s).\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal a intrusion attempt.\n"
"    "
msgstr ""

#: ../src/connect_ports.py:38
#, python-format
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"    where PORT_TYPE is one of the following: %s.\n"
"    "
msgstr ""
"\n"
"    $SOURCE による $PORT_NUMBER への接続を許可する場合は、 以下を実行します。\n"
"\n"
"    # semanage port -a -t PORT_TYPE -p %s $PORT_NUMBER\n"
"\n"
"   ここで、PORT_TYPE は 以下の１つとなります: %s 。\n"
"    "

#: ../src/chrome.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  spice-xpi run "
"applications within mozilla-plugins that require access to the desktop, that "
"the mozilla_plugin lockdown will not allow, so either you need to turn off "
"the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE が要求したアクセスを拒否しました。$SOURCE "
"がこのアクセスを必要とすることは想定されておらず、このアクセスは侵入の試行である可能性があります。アプリケーションの特定のバージョンまたは設定により、追加アクセスが必要となっている可能性もあります。spice-"
"xpi は、デスクトップへのアクセスを必要とする mozilla-plugins 内でアプリケーションを実行し、mozilla_plugin "
"ロックダウンは許可されないことから、mozilla_plugin ロックダウンをオフにするか、これらのパッケージを使用しないようにする必要があります。\n"
" "

#: ../src/chrome.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi', or turn off enforcement of SELinux over the Chrome "
"plugins. setsebool -P unconfined_chrome_sandbox_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger spice-xpi' を実行して mozplluger または spice-xpi "
"のパッケージを削除するか、Chrome プラグインで SELinux の強制をオフにします。setsebool -P "
"unconfined_chrome_sandbox_transition 0\n"
"    "

#: ../src/chrome.py:38 ../src/mozplugger.py:38
#, python-format
msgid "you want to use the %s package"
msgstr "%s パッケージを使用したいです"

#: ../src/chrome.py:43
msgid "you must turn off SELinux controls on the Chrome plugins."
msgstr "Chrome プラグインにおいて SELinux 制御を無効化する必要があります。"

#: ../src/cvs_data.py:27
msgid ""
"\n"
"    SELinux is preventing cvs ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH\n"
"    "
msgstr ""
"\n"
"    SELinux は cvs ($SOURCE_PATH) による $TARGET_PATH への \"$ACCESS\" "
"アクセスを阻止しています\n"
"    "

#: ../src/cvs_data.py:31
msgid ""
"\n"
"    SELinux denied cvs access to $TARGET_PATH.\n"
"    If this is a CVS repository it needs to have a file context label of\n"
"    cvs_data_t. If you did not intend to use $TARGET_PATH as a CVS "
"repository\n"
"    it could indicate either a bug or it could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への cvs アクセスを拒否しました。\n"
"    これが CVS リポジトリーの場合は、 cvs_data_t のファイルコンテキストラベルを \n"
"    持っていなければなりません。CVS リポジトリーとして $TARGET_PATH を\n"
"    使用するつもりではなかった場合、これはバグであるか不正侵入の試行を示している可能性があります。\n"
"    "

#: ../src/cvs_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t cvs_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "
msgstr ""
"\n"
"    chcon -R -t cvs_data_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することが出来ます。\n"
"    "
"また、完全な再ラベルの後でもそれらを維持できるようにするには、システム上のデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t cvs_data_t '$FIX_TARGET_PATH'\"\n"
"    \n"
"    "

#: ../src/cvs_data.py:44
msgid "$TARGET_BASE_PATH should be shared via the cvs daemon"
msgstr "$TARGET_BASE_PATH は cvs デーモンを経由して共有されているべきです。"

#: ../src/cvs_data.py:45 ../src/qemu_file_image.py:49
msgid "You need to change the label on $TARGET_BASE_PATH'"
msgstr "$TARGET_BASE_PATH' のラベルを変更する必要があります。"

#: ../src/dac_override.py:28
msgid "\n"
"    SELinux is preventing $SOURCE_PATH the \"$ACCESS\" capability.\n"
"    "
msgstr ""

#: ../src/dac_override.py:32
msgid ""
"\n"
"\tdac_override and dac_read_search capabilities usually indicates that the "
"root process does not have access to a file based on the permission flags.  "
"This usually mean you have some file with the wrong ownership/permissions on "
"it.\n"
"    "
msgstr ""
"\n"
" \tdac_override と dac_read_search の機能は通常、root プロセスがパーミッションフラグを "
"基にしたファイルへのアクセスを持たないことを表示します。これは通常、ユーザーがそのファイルに 間違えた所有権/"
"パーミッションを持っていることを意味します。 \n"
"    "

#: ../src/dac_override.py:38
msgid ""
"you want to help identify if domain needs this access or you have a file "
"with the wrong permissions on your system"
msgstr "ドメインがこのアクセスを必要とするか、又は使用システム上に間違えたパーミッションで ファイルを所有しているかを確認すると良いでしょう"

#: ../src/dac_override.py:39
msgid ""
"turn on full auditing to get path information about the offending file and "
"generate the error again."
msgstr "全面的な監査を開始して違反しているファイルに関するパス情報を取得し、 再度エラーを生成します。"

#: ../src/dac_override.py:40
msgid ""
"\n"
"Turn on full auditing\n"
"# auditctl -w /etc/shadow -p w\n"
"Try to recreate AVC. Then execute\n"
"# ausearch -m avc -ts recent\n"
"If you see PATH record check ownership/permissions on file, and fix it,\n"
"otherwise report as a bugzilla."
msgstr ""

#: ../src/device.py:29
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" access to device "
"$TARGET_PATH.\n"
"    "
msgstr ""

#: ../src/device.py:33
msgid ""
"\n"
"\n"
"    SELinux has denied $SOURCE \"$ACCESS\" access to device $TARGET_PATH.\n"
"    $TARGET_PATH is mislabeled, this device has the default label of the /"
"dev directory, which should not\n"
"    happen.  All Character and/or Block Devices should have a label.\n"
"\n"
"    You can attempt to change the label of the file using\n"
"\n"
"    restorecon -v '$TARGET_PATH'.\n"
"\n"
"    If this device remains labeled device_t, then this is a bug in SELinux "
"policy.\n"
"\n"
"    Please file a bg report.\n"
"\n"
"    If you look at the other similar devices labels, ls -lZ /dev/SIMILAR, "
"and find a type that would work for $TARGET_PATH,\n"
"    you can use chcon -t SIMILAR_TYPE '$TARGET_PATH', If this fixes the "
"problem, you can make this permanent by executing\n"
"    semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"\n"
"    If the restorecon changes the context, this indicates that the "
"application that created the device, created it without\n"
"    using SELinux APIs.  If you can figure out which application created the "
"device, please file a bug report against this application.\n"
"\n"
"    "
msgstr ""

#: ../src/device.py:56
msgid ""
"\n"
"    Attempt restorecon -v '$TARGET_PATH' or chcon -t SIMILAR_TYPE "
"'$TARGET_PATH'\n"
"    "
msgstr ""
"\n"
"    restorecon -v $TARGET_PATH または chcon -t SIMILAR_TYPE $TARGET_PATH "
"を試してください。\n"
"    "

#: ../src/device.py:60
msgid ""
"You need to change the label on $TARGET_PATH to a type of a similar device."
msgstr "$TARGET_PATH のラベルを同種のデバイスのタイプに変更する必要があります。"

#: ../src/device.py:61
msgid ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t SIMILAR_TYPE '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/disable_ipv6.py:30
msgid "\n"
"Disable IPV6 properly.\n"
"    "
msgstr "\n"
"IPv6 を正しく無効化しました。\n"
"    "

#: ../src/disable_ipv6.py:40
msgid "you want to disable IPV6 on this machine"
msgstr "このマシンにおいて IPv6 を無効化したいです"

#: ../src/disable_ipv6.py:41
msgid ""
"you need to set /proc/sys/net/ipv6/conf/all/disable_ipv6 to 1 and do not "
"blacklist the module'"
msgstr ""
"/proc/sys/net/ipv6/conf/all/disable_ipv6 を 1 に設定する必要があり、モジュールをブラックリストにしません。"

#: ../src/disable_ipv6.py:42
msgid "Add \n"
"net.ipv6.conf.all.disable_ipv6 = 1\n"
"to /etc/sysctl.conf\n"
msgstr "net.ipv6.conf.all.disable_ipv6 = 1 を\n"
"/etc/sysctl.conf に追加します\n"

#: ../src/file.py:27
msgid ""
"\n"
"    SELinux is preventing access to files with the label, file_t.\n"
"    "
msgstr "\n"
"    SELinux は file_t ラベルが付いたファイルへのアクセスを阻止しています。\n"
"    "

#: ../src/file.py:31
msgid ""
"\n"
"    SELinux permission checks on files labeled file_t are being\n"
"    denied.  file_t is the context the SELinux kernel gives to files\n"
"    that do not have a label. This indicates a serious labeling\n"
"    problem. No files on an SELinux box should ever be labeled file_t.\n"
"    If you have just added a disk drive to the system you can\n"
"    relabel it using the restorecon command.  For example if you saved the\n"
"home directory from a previous installation that did not use SELinux, "
"'restorecon -R -v /home' will fix the labels.  Otherwise you should\n"
"    relabel the entire file system.\n"
"    "
msgstr ""
"\n"
"file_t のラベルが付いたファイル上の SELinux 権限チェックは拒否⏎ されています。file_t は、SELinux "
"カーネルがラベルを持たないファイルに付与するコンテキストです。これは真剣なラベル付けの問題を⏎ 示します。SELinux ボックス上のファイルはいずれも "
"file_t のラベルを付けるべきものではありません。システムにディスクドライブを追加したばかりの場合は、restorecon "
"コマンドを使用してラベルの変更ができます。例えば、SELinux "
"を使用していない以前のインストールからホームディレクトリを保存した場合、'restorecon -R -v /home' "
"でラベルを修正できます。　それ以外には、全てのファイルシステムをラベル変更する必要があります。"

#: ../src/file.py:42
msgid ""
"\n"
"    You can execute the following command as root to relabel your\n"
"    computer system: \"touch /.autorelabel; reboot\"\n"
"    "
msgstr ""
"\n"
"    root として次のコマンドを実行するとご使用のコンピュータを再ラベルする\n"
"    ことができます: \"touch /.autorelabel; reboot\"\n"
"    "

#: ../src/file.py:49
msgid "this is caused by a newly created file system."
msgstr "これは新規作成されたファイルシステムによって引き起こされたものです。"

#: ../src/file.py:51
msgid "you think this is caused by a badly mislabeled machine."
msgstr "これは間違ったラベルを付けられたマシンによって起こされました"

#: ../src/file.py:55
msgid "you need to add labels to it."
msgstr "これにラベルを追加する必要があります。"

#: ../src/file.py:57
msgid "you need to fully relabel."
msgstr "すべてにラベルを付け直す必要があります。"

#: ../src/filesystem_associate.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH from creating a file with a context "
"of $SOURCE_TYPE on a filesystem.\n"
"    "
msgstr ""
"\n"
"      SELinux は $SOURCE_PATH がファイルシステム上で $SOURCE_TYPE "
"のコンテキストでファイルを作成することを阻止しています。\n"
"      "

#: ../src/filesystem_associate.py:31
msgid ""
"\n"
"    SELinux is preventing $SOURCE from creating a file with a context of "
"$SOURCE_TYPE on a filesystem.\n"
"    Usually this happens when you ask the cp command to maintain the context "
"of a file when\n"
"    copying between file systems, \"cp -a\" for example.  Not all file "
"contexts should be maintained\n"
"    between the file systems.  For example, a read-only file type like "
"iso9660_t should not be placed\n"
"    on a r/w system.  \"cp -p\" might be a better solution, as this will "
"adopt the default file context\n"
"    for the destination.\n"
"    "
msgstr ""

#: ../src/filesystem_associate.py:40
msgid ""
"\n"
"    Use a command like \"cp -p\" to preserve all permissions except SELinux "
"context.\n"
"    "
msgstr "\n"
"     \"cp -p\" などのコマンドを使用して、SELinux コンテキスト以外の全ての権限を保存します。\n"
"     "

#: ../src/filesystem_associate.py:43
msgid ""
"you believe $SOURCE_BASE_PATH should be allowed to create $TARGET_BASE_PATH "
"files"
msgstr "$SOURCE_BASE_PATH は、 $TARGET_BASE_PATH ファイルを作成するために許可されているべきです。"

#: ../src/filesystem_associate.py:44
msgid ""
"you need to use a different command. You are not allowed to preserve the "
"SELinux context on the target file system."
msgstr ""
"別のコマンドを使用する必要があります。あなたはターゲットのファイルシステムで、SELinux コンテンツを保存することが許可されていません。"

#: ../src/filesystem_associate.py:46
msgid ""
"use a command like \"cp -p\" to preserve all permissions except SELinux "
"context."
msgstr "\"cp -p\" などのコマンドを使用して、SELinux コンテキスト以外の全ての権限を保存します。     "

#: ../src/httpd_can_sendmail.py:28
msgid "\n"
"    SELinux is preventing the http daemon from sending mail.\n"
"    "
msgstr "\n"
"    SELinux は http デーモンによるメール送信を阻止しています。\n"
"    "

#: ../src/httpd_can_sendmail.py:32
msgid ""
"\n"
"    SELinux has denied the http daemon from sending mail. An\n"
"    httpd script is trying to connect to a mail port or execute the\n"
"    sendmail command. If you did not setup httpd to sendmail, this could\n"
"    signal a intrusion attempt.\n"
"    "
msgstr ""

#: ../src/httpd_can_sendmail.py:39
msgid ""
"\n"
"    If you want httpd to send mail you need to turn on the\n"
"    $BOOLEAN boolean: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"    httpd にメール送信をさせる場合は、 $BOOLEAN boolean\n"
"    をオンにする必要があります: \"setsebool -P\n"
"    $BOOLEAN=1\"\n"
"    "

#: ../src/httpd_can_sendmail.py:47
msgid "you want to allow httpd to send mail"
msgstr "httpd が、メール送信することを、許可したい"

#: ../src/httpd_can_sendmail.py:48
msgid "you must setup SELinux to allow this"
msgstr "これを許可するには、SELinux を設定しなければいけません"

#: ../src/httpd_unified.py:29
msgid "\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"    "
msgstr "\n"
"      httpdの、 http ファイルへの $ACCESS アクセスを、SELinux は阻止しました。\n"
"    "

#: ../src/httpd_unified.py:33
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to http files.\n"
"\n"
"    Ordinarily httpd is allowed full access to all files labeled with http "
"file\n"
"    context.  This machine has a tightened security policy with the $BOOLEAN\n"
"    turned off,  This requires explicit labeling of all files.  If a file is\n"
"    a cgi script it needs to be labeled with httpd_TYPE_script_exec_t in "
"order\n"
"    to be executed.  If it is read only content, it needs to be labeled\n"
"    httpd_TYPE_content_t, it is writable content. it needs to be labeled\n"
"    httpd_TYPE_script_rw_t or httpd_TYPE_script_ra_t. You can use the\n"
"    chcon command to change these context.  Please refer to the man page\n"
"    \"man httpd_selinux\" or\n"
"    <a href=\"http://fedora.redhat.com/docs/selinux-apache-fc3\">FAQ</a>\n"
"    \"TYPE\" refers to one of \"sys\", \"user\" or \"staff\" or potentially "
"other\n"
"    script types.\n"
"    "
msgstr ""

#: ../src/httpd_unified.py:50
msgid ""
"\n"
"    Changing the \"$BOOLEAN\" boolean to true will allow this access:\n"
"    \"setsebool -P $BOOLEAN=1\"\n"
"    "
msgstr ""
"\n"
"     \"$BOOLEAN\" boolean 値を「true」に変更すると、このアクセスを許可します：\n"
"     \"setsebool -P $BOOLEAN=1\"\n"
"     "

#: ../src/httpd_unified.py:57
msgid ""
"you want to allow httpd to execute cgi scripts and to unify HTTPD handling "
"of all content files."
msgstr "httpd による cgi スクリプトの実行、 および全コンテンツファイルの HTTPD 処理の統一を許可します。"

#: ../src/httpd_unified.py:58
msgid ""
"you must tell SELinux about this by enabling the 'httpd_unified' and "
"'http_enable_cgi' booleans"
msgstr ""
"これについては、SELinux で 'httpd_unified' と 'http_enable_cgi' booleans "
"を有効にしなければいけません"

#: ../src/httpd_write_content.py:30
msgid ""
"\n"
"    SELinux prevented httpd $ACCESS access to $TARGET_PATH.\n"
"\n"
"    httpd scripts are not allowed to write to content without explicit\n"
"    labeling of all files.  If $TARGET_PATH is writable content. it needs\n"
"    to be labeled httpd_sys_rw_content_t or if all you need is append you "
"can label it httpd_sys_ra_content_t.   Please refer to 'man httpd_selinux' "
"for more information on setting up httpd and selinux.\n"
"    "
msgstr ""

#: ../src/httpd_write_content.py:40 ../src/qemu_blk_image.py:45
#: ../src/samba_share.py:45 ../src/swapfile.py:46 ../src/xen_image.py:48
msgid "You need to change the label on '$FIX_TARGET_PATH'"
msgstr "'$FIX_TARGET_PATH' のラベルを変更する必要があります"

#: ../src/kernel_modules.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"kernel configuration.\n"
"    "
msgstr "\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH がカーネル設定を変更しようとしました。\n"
"    "

#: ../src/kernel_modules.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the way the kernel runs or to\n"
"    actually insert code into the kernel. All applications that need this\n"
"    access should have already had policy written for them.  If a "
"compromised\n"
"    application tries to modify the kernel this AVC will be generated. This "
"is a\n"
"    serious issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/kernel_modules.py:44 ../src/selinuxpolicy.py:44
msgid ""
"you do not think $SOURCE_BASE_PATH should try $ACCESS access on "
"$TARGET_BASE_PATH."
msgstr ""
"$SOURCE_BASE_PATH が $TARGET_BASE_PATH の  $ACCESS access を試みるべきではありません。   "

#: ../src/kernel_modules.py:45 ../src/selinuxpolicy.py:45
msgid ""
"you may be under attack by a hacker, since confined applications should not "
"need this access."
msgstr "制限したアプリケーションではこのアクセスは必要とされないため、 ハッカーから攻撃を受けている可能性があります。"

#: ../src/leaks.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH access to a leaked $TARGET_PATH file "
"descriptor.\n"
"    "
msgstr ""
"\n"
"    SELinux は 漏洩した $TARGET_PATH のファイル記述子へ $SOURCE_PATH  がアクセスすることを阻止しています。\n"
"    "

#: ../src/leaks.py:31
msgid ""
"\n"
"    SELinux denied access requested by the $SOURCE command. It looks like "
"this is either a leaked descriptor or $SOURCE output was redirected to a "
"file it is not allowed to access.  Leaks usually can be ignored since "
"SELinux is just closing the leak and reporting the error.  The application "
"does not use the descriptor, so it will run properly.  If this is a "
"redirection, you will not get output in the $TARGET_PATH.  You should "
"generate a bugzilla on selinux-policy, and it will get routed to the "
"appropriate package.  You can safely ignore this avc.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE コマンドにより要求されたアクセスを拒否しました。これは、 リークした記述子か、又は $SOURCE "
"の出力がアクセスの許可がないファイルへ再転送 されたように見えます。SELinux がリークを閉じてエラーを報告するため、リークは通常 "
"無視されます。アプリケーションは正常の稼働するように記述子を使用しません。これが 再転送であった場合、$TARGET_PATH "
"には出力を得ることはありません。selinux-policy 上に bugzilla "
"を生成すべきで、そうすると、それが適切なパッケージまで巡回します。この avc は 無視しても安全です。\n"
"     "

#: ../src/leaks.py:35
msgid ""
"\n"
"    You can generate a local policy module to allow this\n"
"    access - see <a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a>\n"
"    "
msgstr ""
"\n"
"    ローカルポリシーモジュールを生成して、このアクセスを許可するように\n"
"    できます：<a href=\"http://docs.fedoraproject.org/selinux-faq-fc5/"
"#id2961385\">FAQ</a> をご覧下さい。\n"
"    "

#: ../src/leaks.py:42
msgid ""
"you want to ignore $SOURCE_BASE_PATH trying to $ACCESS access the "
"$TARGET_BASE_PATH $TARGET_CLASS, because you believe it should not need this "
"access."
msgstr ""
"$SOURCE_BASE_PATH が、 $TARGET_BASE_PATH $TARGET_CLASS へ $ACCESS "
"アクセスを試みることを、拒否したい。このアクセスが必要とは思えないため。"

#: ../src/leaks.py:43
msgid ""
"You should report this as a bug.  \n"
"You can generate a local policy module to dontaudit this access."
msgstr "バグとして報告してください。  \n"
"ローカルのポリシーモジュールを生成すると、このアクセスを監査しないようにすることができます。"

#: ../src/leaks.py:44
msgid ""
"# ausearch -x $SOURCE_PATH --raw | audit2allow -D -M mypol\n"
"# semodule -i mypol.pp"
msgstr ""

#: ../src/mmap_zero.py:29
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH attempted to mmap "
"low kernel memory.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH が低位置カーネルメモリーへの mmap を試行しました。\n"
"    "

#: ../src/mmap_zero.py:33
msgid ""
"\n"
"    SELinux has denied the $SOURCE the ability to mmap low area of the "
"kernel \n"
"    address space.  The ability to mmap a low area of the address space, as \n"
"    configured by /proc/sys/kernel/mmap_min_addr.  Preventing such mappings \n"
"    helps protect against exploiting null deref bugs in the kernel. All \n"
"    applications that need this access should have already had policy "
"written \n"
"    for them.  If a compromised application tries modify the kernel this AVC "
"\n"
"    would be generated. This is a serious issue. Your system may very well "
"be \n"
"    compromised.\n"
"    "
msgstr ""
"\n"
"    SELinux は カーネルアドレススペースの低位置を mmap する $SOURCE の 機能を\n"
" 拒否しました。アドレススペースの低位置を mmap する機能は、\n"
"/proc/sys/kernel/mmap_min_addr で設定されます。 このようなマッピングを拒否すると、 \n"
"カーネル内での null deref バグの悪用を防止する手助けになります。 このアクセスを\n"
"必要とするアプリケーションはすべて独自のポリシーが記述されているはずです。\n"
"セキュリティ侵害されたアプリケーションによりカーネルの修正が試行されると、 \n"
"この AVC が生成されます。 これは深刻な問題となります。 ご使用のシステムは非常に\n"
"高い確率でセキュリティ侵害されている可能性があります。\n"
"    "

#: ../src/mmap_zero.py:46
msgid ""
"you do not think $SOURCE_PATH should need to mmap low memory in the kernel."
msgstr "$SOURCE_PATH にカーネル内で低いメモリーの mmap を行なう必要があるとは思えません。"

#: ../src/mmap_zero.py:47
msgid "you may be under attack by a hacker, this is a very dangerous access."
msgstr "ハッカーから攻撃されている可能性があります。これは非常に危険なアクセスです。"

#: ../src/mounton.py:29
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting on the file or directory\n"
"    \"$TARGET_PATH\" (type \"$TARGET_TYPE\").\n"
"    "
msgstr ""
"\n"
"SELinux により \"$TARGET_PATH\" という名前のファイルまたはディレクトリ \n"
"(タイプ \"$TARGET_TYPE\") での $SOURCE によるマウントが阻止されました。\n"
"     "

#: ../src/mounton.py:34
msgid ""
"\n"
"    SELinux prevented $SOURCE from mounting a filesystem on the file\n"
"    or directory \"$TARGET_PATH\" of type \"$TARGET_TYPE\". By default\n"
"    SELinux limits the mounting of filesystems to only some files or\n"
"    directories (those with types that have the mountpoint attribute). The\n"
"    type \"$TARGET_TYPE\" does not have this attribute. You can change the\n"
"    label of the file or directory.\n"
"    "
msgstr ""

#: ../src/mounton.py:43
msgid ""
"\n"
"    Changing the file_context to mnt_t will allow mount to mount the file "
"system:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"mnt_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    file_context を mnt_t に変更すると、mount によるファイルシステムのマウントが 許可されます:\n"
"    \"chcon -t mnt_t '$TARGET_PATH'.\"\n"
"    また、完全な再ラベルの後でもそれらを保持できるように、システム上でデフォルトの "
"ファイルコンテキストファイルの変更もしなければなりません。\"semanage fcontext -a -t mnt_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/mounton.py:48
msgid "you want to allow $SOURCE_BASE_PATH to mount on $TARGET_BASE_PATH."
msgstr "$SOURCE_BASE_PATH が、 $TARGET_BASE_PATH 上でマウントすることを、許可したい。"

#: ../src/mounton.py:49
msgid "you must change the labeling on $TARGET_PATH."
msgstr "$TARGET_PATH のラベルを変更しなければいけません。"

#: ../src/mozplugger.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not expected that this "
"access is required by $SOURCE and this access may signal an intrusion "
"attempt. It is also possible that the specific version or configuration of "
"the application is causing it to require additional access.  mozplugger and "
"spice-xpi run applications within mozilla-plugins that require access to the "
"desktop, that the mozilla_plugin lockdown will not allow, so either you need "
"to turn off the mozilla_plugin lockdown or not use these packages.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE が要求したアクセスを拒否しました。$SOURCE "
"がこのアクセスを必要とすることは想定されておらず、このアクセスは侵入の試行である可能性があります。アプリケーションの特定のバージョンまたは設定により、追加アクセスが必要となっている可能性もあります。mozplugger "
"および spice-xpi は、デスクトップへのアクセスを必要とする mozilla-plugins "
"内でアプリケーションを実行し、mozilla_plugin ロックダウンは許可されないことから、mozilla_plugin "
"ロックダウンをオフにするか、これらのパッケージを使用しないようにする必要があります。\n"
" "

#: ../src/mozplugger.py:35
msgid ""
"\n"
"Either remove the mozplugger or spice-xpi package by executing 'yum remove "
"mozplugger spice-xpi' or turn off enforcement of SELinux over the Firefox "
"plugins. setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger spice-xpi' を実行して mozplluger または spice-xpi "
"のパッケージを削除するか、Firefox プラグインで SELinux の強制をオフにします。setsebool -P "
"unconfined_mozilla_plugin_transition 0"

#: ../src/mozplugger.py:43
msgid "you must turn off SELinux controls on the Firefox plugins."
msgstr "Firefox プラグインで SELinux の制御を全てオフにする必要があります。"

#: ../src/mozplugger_remove.py:31
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. It is not\n"
"    expected that this access is required by $SOURCE and this access\n"
"    may signal an intrusion attempt. It is also possible that the specific\n"
"    version or configuration of the application is causing it to require\n"
"    additional access.\n"
"    "
msgstr ""
"\n"
"$SOURCE から要求されたアクセスは SELinux が拒否しました。⏎ このアクセスは $SOURCE で必要であると予測されていないため、⏎ "
"このアクセスは侵害の形跡かも知れません。また、アプリケーションの特定の⏎ バージョン、又は設定が余分なアクセスを要求する原因である可能性も⏎ あります。"

#: ../src/mozplugger_remove.py:39
msgid ""
"\n"
"Either remove the mozplluger package by executing 'yum remove mozplugger'\n"
"Or turn off enforcement of SELinux over the Firefox plugins.\n"
"setsebool -P unconfined_mozilla_plugin_transition 0\n"
"    "
msgstr ""
"\n"
"'yum remove mozplugger' を実行して mozplluger パッケージを削除するか、⏎ あるいは Firefox プラグイン上の "
"SELinux の強制をオフにします。⏎ setsebool -P unconfined_mozilla_plugin_transition 0⏎ "

#: ../src/mozplugger_remove.py:44
msgid ""
"you want to to continue using SELinux Firefox plugin containment rather then "
"using mozplugger package"
msgstr "mozplugger パッケージではなく、SELinux Firefox プラグインの内容を続けて使用したいとします。"

#: ../src/mozplugger_remove.py:45
msgid "you must remove the mozplugger package."
msgstr "mozplugger パッケージを削除する必要があります。"

#: ../src/openvpn.py:35
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be a mislabeled. openvpn is allowed to read content in home directory if "
"it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/openvpn.py:41 ../src/sshd_root.py:42
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon restore using restorecon -R /root/.ssh.\n"
"    "
msgstr ""
"\n"
"    restorecon コマンドを実行することにより、このファイルへデフォルトのシステムコンテキストを\n"
"    復元することが出来ます。restorecon は restorecon -R /root/.ssh を使用して \n"
"復元します。"

#: ../src/openvpn.py:48
msgid ""
"you want to mv $TARGET_BASE_PATH to standard location so that "
"$SOURCE_BASE_PATH can have $ACCESS access"
msgstr ""
"$SOURCE_BASE_PATH が $ACCESS へアクセスできるよう、 $TARGET_BASE_PATH を標準の場所に移動したい"

#: ../src/openvpn.py:50
msgid ""
"you want to modify the label on $TARGET_BASE_PATH so that $SOURCE_BASE_PATH "
"can have $ACCESS access on it"
msgstr "$SOURCE_BASE_PATH が $ACCESS へアクセスできるよう、 $TARGET_BASE_PATH のラベルを編集したい"

#: ../src/openvpn.py:54
msgid "you must move the cert file to the ~/.cert directory"
msgstr "cert ファイルを ~/.cert directory に移動しなければいけません"

#: ../src/openvpn.py:56 ../src/sshd_root.py:47
msgid "you must fix the labels."
msgstr "ラベルを修正しなければいけません。"

#: ../src/public_content.py:31
msgid ""
"\n"
"    SELinux denied access to $TARGET_PATH requested by $SOURCE.\n"
"    $TARGET_PATH has a context used for sharing by a different program. If "
"you\n"
"    would like to share $TARGET_PATH from $SOURCE also, you need to\n"
"    change its file context to public_content_t.  If you did not intend to\n"
"    allow this access, this could signal an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux で $SOURCE が要求した $TARGET_PATH へのアクセスが拒否されました。\n"
"$TARGET_PATH には、 別のプログラムで共有に使用されるコンテキストがあります。\n"
"$SOURCE からも $TARGET_PATH を共有したい場合、 そのファイルコンテキストを \n"
"public_content_t に変更する必要があります。 このアクセスを意図的に許可して\n"
"いなかった場合、 不正侵入が行なわれた可能性があります。\n"
"    "

#: ../src/public_content.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -t public_content_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"public_content_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"chcon -t public_content_t '$TARGET_PATH' を実行すると、 ファイルのコンテキストを\n"
"変更することができます。 また、 完全な再ラベル付けが行なわれた後も変更した\n"
"ファイルコンテキストを維持させたい場合には、 システム上でデフォルトのファイル\n"
"コンテキストのファイルも変更する必要があります。 \"semanage fcontext -a -t public_content_t "
"'$FIX_TARGET_PATH'\"    "

#: ../src/public_content.py:50
msgid "you want to treat $TARGET_BASE_PATH as public content"
msgstr "$TARGET_BASE_PATH を公開コンテンツとして処理します"

#: ../src/public_content.py:51
msgid ""
"You need to change the label on $TARGET_BASE_PATH to public_content_t or "
"public_content_rw_t."
msgstr ""
"$TARGET_BASE_PATH のラベルを public_content_t または public_content_rw_t "
"に変更する必要があります。"

#: ../src/qemu_blk_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to the block device $TARGET_PATH.\n"
"    If this is a virtualization image, it needs to be labeled with a "
"virtualization file context (virt_image_t). You can relabel $TARGET_PATH to "
"be virt_image_t using chcon.  You also need to execute semanage fcontext -a -"
"t virt_image_t '$FIX_TARGET_PATH' to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux はブロックデバイス $TARGET_PATH への qemu のアクセスを拒否しました。\n"
"    これが仮想化イメージの場合は、仮想化ファイルコンテキスト (virt_image_t) でラベルが付けられる必要があります。chcon "
"を使用して $TARGET_PATH を virt_image_t  に 再度ラベル付けすることができます。 また、semanage fcontext -"
"a - t virt_image_t '$FIX_TARGET_PATH'も 実行して、この新しいパスをシステムデフォルトに    "
"追加する必要があります。$TARGET_PATH を qemu イメージとして使用するつもりでなかった場合は、\n"
"     それは、バグを示すか、又は不正侵入の試みを示すことになります。\n"
"    "

#: ../src/qemu_blk_image.py:38 ../src/qemu_file_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t virt_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"   chcon  -t virt_image_t '$TARGET_PATH' を実行すると、ファイルコンテキストの 変更ができます。\n"
"    "
"また、完全な再ラベルの後でもそれらが保持できるようにシステム上でデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/qemu_blk_image.py:46
msgid ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH'\n"
"# restorecon -v '$FIX_TARGET_PATH'"

#: ../src/qemu_file_image.py:31
msgid ""
"\n"
"    SELinux denied qemu access to $TARGET_PATH.\n"
"    If this is a virtualization image, it has to have a file context label "
"of\n"
"    virt_image_t. The system is setup to label image files in directory./var/"
"lib/libvirt/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/"
"libvirt/images.\n"
"    If you really want to have your qemu image files in the current "
"directory, you can relabel $TARGET_PATH to be virt_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a qemu\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
" SELinux により $TARGET_PATH への qemu のアクセスが拒否されました。\n"
"これが仮想化イメージの場合は、 virt_image_t のファイルコンテキストラベルを持たせる\n"
"必要があります。 システムは /var/lib/libvirt/images ディレクトリ内でイメージファイル\n"
"のラベル付けを行なうよう正しく設定されています。 使用するイメージファイルを \n"
"var/lib/libvirt/images にコピーすることをお勧めします。 qemu イメージファイルを\n"
"どうしても現在のディレクトリ内に配置する必要がある場合は、 chcon を使用して \n"
"$TARGET_PATH に virt_image_t  のラベルを付け直してください。 また、\n"
"semanage fcontext -a -t virt_image_t '$FIX_TARGET_PATH' を実行して、 この新しいパスを\n"
"システムのデフォルト設定に追加する必要があります。 $TARGET_PATH を qemu イメージ\n"
"として使用する意図がなかった場合は、 バグまたは不正侵入の試行を示している可能性があります。"

#: ../src/qemu_file_image.py:48
msgid "$TARGET_BASE_PATH is a virtualization target"
msgstr "$TARGET_BASE_PATH は仮想的なターゲットです"

#: ../src/restorecon.py:48
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$TARGET_PATH', if this file is a "
"directory,\n"
"    you can recursively restore using restorecon -R '$TARGET_PATH'.\n"
"    "
msgstr ""
"\n"
"restorecon コマンドを実行することにより、 このファイルにデフォルトの\n"
"システムコンテキストを復元することができます (restorecon '$TARGET_PATH')。\n"
"このファイルがディレクトリの場合には、 restorecon -R '$TARGET_PATH' を\n"
"使用して再帰的に復元することができます。\n"
"    "

#: ../src/restorecon.py:55
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be a mislabeled.  $TARGET_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$TARGET_TYPE</B>. Changing\n"
"    this file back to the default type, may fix your problem.\n"
"    <p>\n"
"    File contexts can be assigned to a file in the following ways.\n"
"    <ul>\n"
"        <li>Files created in a directory receive the file context of the "
"parent directory by default.\n"
"        <li>The SELinux policy might override the default label inherited "
"from the parent directory by\n"
"            specifying a process running in context A which creates a file "
"in a directory labeled B\n"
"            will instead create the file with label C. An example of this "
"would be the dhcp client running\n"
"            with the dhclient_t type and creating a file in the directory /"
"etc. This file would normally\n"
"            receive the etc_t type due to parental inheritance but instead "
"the file\n"
"            is labeled with the net_conf_t type because the SELinux policy "
"specifies this.\n"
"        <li>Users can change the file context on a file using tools such as "
"chcon, or restorecon.\n"
"    </ul>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon.py:81
#, python-format
msgid "you want to fix the label. \n"
"$TARGET_PATH default label should be %s."
msgstr "ラベルを修正することになります。\n"
"$TARGET_PATH のデフォルトラベルは %s のはずです。"

#: ../src/restorecon.py:86 ../src/restorecon_source.py:65
msgid "you can run restorecon."
msgstr "restorecon を実行することができます。"

#: ../src/restorecon.py:94 ../src/restorecon_source.py:73
msgid "Restore\n"
"Context"
msgstr "コンテキストの\n"
"復元"

#: ../src/restorecon_source.py:39
msgid ""
"\n"
"    You can restore the default system context to this file by executing the\n"
"    restorecon command.  restorecon '$SOURCE_PATH'.\n"
"    "
msgstr ""
"\n"
"    restorecon コマンドを実行することにより、このファイルのコンテキストを\n"
"    システムの初期値に復元できます。 restorecon '$SOURCE_PATH' 。\n"
"    "

#: ../src/restorecon_source.py:45
#, python-format
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $SOURCE_PATH may\n"
"    be a mislabeled.  $SOURCE_PATH default SELinux type is\n"
"    <B>%s</B>, but its current type is <B>$SOURCE_TYPE</B>. Changing\n"
"    this file back to the default type, may fix your problem.\n"
"    <p>\n"
"    This file could have been mislabeled either by user error, or if an "
"normally confined application\n"
"    was run under the wrong domain.\n"
"    <p>\n"
"    However, this might also indicate a bug in SELinux because the file "
"should not have been labeled\n"
"    with this type.\n"
"    <p>\n"
"    If you believe this is a bug, please file a bug report against this "
"package.\n"
"    "
msgstr ""

#: ../src/restorecon_source.py:60
#, python-format
msgid "you want to fix the label. \n"
"$SOURCE_PATH default label should be %s."
msgstr "ラベルを修正することになります。 \n"
"$SOURCE_PATH の標準ランレベルは %s のはずです。"

#: ../src/rsync_data.py:31
msgid ""
"\n"
"    SELinux denied rsync access to $TARGET_PATH.\n"
"    If this is a RSYNC repository it has to have a file context label of\n"
"    rsync_data_t. If you did not intend to use $TARGET_PATH as a rsync "
"repository\n"
"    it could indicate either a bug or it could signal a intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は rsync が $TARGET_PATH にアクセスするのを拒否しました。\n"
"     これが、RSYNC のレポジトリーであるなら、rsync_data_t のファイル \n"
"    コンテキストラベルを持っている必要があります。$TARGET_PATH を \n"
"    rsync レポジトリーとして使用する予定でなかった場合、これはバグか、\n"
"     あるいは、侵入の試みを示します。\n"
"    "

#: ../src/rsync_data.py:38
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t rsync_data_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -R -t rsync_data_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することが出来ます。\n"
"    また、それらを完全な再ラベルの後でも保持できるようにシステム上でデフォルトのファイルコンテキストも変更しなければなりません。\"semanage "
"fcontext -a -t rsync_data_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/rsync_data.py:45
msgid "$TARGET_BASE_PATH should be shared via the rsync daemon"
msgstr "$TARGET_BASE_PATH は rsync デーモンによって共有されるべきです"

#: ../src/rsync_data.py:46
msgid "You need to change the label on $TARGET_BASE_PATH"
msgstr "$TARGET_BASE_PATH のラベルを変更する必要があります。"

#: ../src/samba_share.py:27
msgid ""
"\n"
"    SELinux is preventing Samba ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への Samba ($SOURCE_PATH) による \"$ACCESS\" "
"アクセスを阻止しています。\n"
"    "

#: ../src/samba_share.py:31
msgid ""
"\n"
"    SELinux denied samba access to $TARGET_PATH.\n"
"    If you want to share this directory with samba it has to have a file "
"context label of\n"
"    samba_share_t. If you did not intend to use $TARGET_PATH as a samba "
"repository\n"
"    it could indicate either a bug or it could signal a intrusion attempt.\n"
"    Please refer to 'man samba_selinux' for more information on setting up "
"Samba and SELinux.\n"
"    "
msgstr ""
"\n"
"    SELinux は samba が $TARGET_PATH へアクセスするのを拒否しました。\n"
"     このディレクトリを samba で共有したい場合、samba_share_t の \n"
"    ファイルコンテキストラベルを持っている必要があります。$TARGET_PATH を \n"
"    samba レポジトリとして使用する意図で無かった場合、これはバグか、又は \n"
"    侵入の試みの形跡を意味します。Samba と SELinux のセットアップに関する 詳細には 'man samba_selinux' "
"を参照して下さい。    \n"
"    "

#: ../src/samba_share.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -R -t samba_share_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -R -t samba_share_t '$TARGET_PATH' を実行すると、ファイルコンテキストを変更することができます。\n"
"    "
"また、完全な再ラベルの後にもそれらを保持するためにシステム上でデフォルトのファイルコンテキストファイルも変更しなければなりません。\"semanage "
"fcontext -a -t samba_share_t '$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/samba_share.py:53
#, python-format
msgid ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"
msgstr ""
"# semanage fcontext -a -t samba_share_t '$FIX_TARGET_PATH%s'\n"
"# restorecon %s -v '$FIX_TARGET_PATH'"

#: ../src/sandbox_connect.py:33
msgid ""
"\n"
"    SELinux has denied $SOURCE from connecting to a network port "
"$PORT_NUMBER within a sandbox.\n"
"    If $SOURCE should be allowed to connect on $PORT_NUMBER, you need to use "
"a different sandbox type like sandbox_web_t or sandbox_net_t.  sandbox -X -t "
"sandbox_net_t $SOURCE.\n"
"    \n"
"\n"
"If $SOURCE is not supposed\n"
"    to connect to $PORT_NUMBER, this could signal a intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は、$SOURCE が sandboxt の中でネットワークポート $PORT_NUMBER に接続することを拒否しました。\n"
"    $SOURCE による $PORT_NUMBER への接続を許可する場合、他の sandbox_web_t や sandbox_net_t "
"のようなサンドボックスタイプを使用する必要があります。sandbox -X -t sandbox_net_t $SOURCE を実行してください。\n"
"    \n"
"\n"
"$SOURCE による $PORT_NUMBER への接続が想定されていない場合、\n"
"    これは侵入の試みである可能性があります。\n"
"    "

#: ../src/sandbox_connect.py:40
msgid ""
"\n"
"    If you want to allow $SOURCE to connect to $PORT_NUMBER, you can execute "
"\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "
msgstr ""
"\n"
"    $SOURCE による $PORT_NUMBER への接続を許可する場合は、以下を実行します。\n"
"\n"
"    # sandbox -X -t sandbox_net_t $SOURCE\n"
"    "

#: ../src/sandbox_connect.py:46
msgid "you want to allow $SOURCE_PATH to connect to network port $PORT_NUMBER"
msgstr "$SOURCE_PATH がネットワークポート $PORT_NUMBER に接続したい場合"

#: ../src/sandbox_connect.py:48
msgid ""
"you need to modify the sandbox type. sandbox_web_t or sandbox_net_t.\n"
"For example:\n"
"sandbox -X -t sandbox_net_t $SOURCE_PATH\n"
"Please read 'sandbox' man page for more details.\n"
msgstr ""

#: ../src/selinuxpolicy.py:29
msgid "\n"
"    Your system may be seriously compromised!\n"
"    "
msgstr "\n"
"    ご使用のシステムには深刻な侵害の可能性があります! \n"
"    "

#: ../src/selinuxpolicy.py:33
msgid ""
"\n"
"    SELinux has prevented $SOURCE from modifying $TARGET.  This denial\n"
"    indicates $SOURCE was trying to modify the selinux policy configuration.\n"
"    All applications that need this access should have already had policy\n"
"    written for them.  If a compromised application tries to modify the "
"SELinux\n"
"    policy this AVC will be generated. This is a serious issue. Your system\n"
"    may very well be compromised.\n"
"    "
msgstr ""

#: ../src/setenforce.py:27
msgid "you did not directly cause this AVC through testing."
msgstr "このAVCはこのテストによって直接起こったものではありません。"

#: ../src/setenforce.py:28
msgid "if you think that you might have been hacked"
msgstr "これがハッキングされていると考える場合"

#: ../src/setenforce.py:32
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to modify "
"SELinux enforcement.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH が SELinux 強制を修正しようとしました。\n"
"    "

#: ../src/setenforce.py:36
msgid ""
"\n"
"    SELinux has prevented $SOURCE from writing to a file under /selinux.\n"
"    Files under /selinux control the way SELinux is configured.\n"
"    All programs that need to write to files under /selinux should have "
"already had policy\n"
"    written for them. If a compromised application tries to turn off SELinux\n"
"    this AVC will be generated. This is a serious issue. Your system may "
"very\n"
"    well be compromised.\n"
"    "
msgstr ""
"\n"
"    SELinux は $SOURCE による /selinux 以下のファイルへの書き込みを阻止しました。\n"
"    /selinux 下のファイルは SELinux が設定される方法を制御します。\n"
"    /selinux 下にファイルを書き込む必要のある全てのプログラムはそれ自身用に すでにポリシーを\n"
"    書かせておくべきでした。侵害されたアプリケーションが SELinux を閉じる 試みをすると\n"
"    この AVC が生成されるでしょう。これは重大な問題です。ご使用のシステムは 既に\n"
"    侵害されている可能性があります。\n"
"    "

#: ../src/setenforce.py:48
msgid "you believe $SOURCE_PATH tried to disable SELinux."
msgstr "$SOURCE_PATH が SELinux を無効にしようとしました。"

#: ../src/setenforce.py:49
msgid ""
"you may be under attack by a hacker, since confined applications should "
"never need this access."
msgstr "このアクセスが制限したアプリケーションで必要とされることは絶対にないため、 ハッカーからの攻撃を受けている可能性があります。"

#: ../src/sshd_root.py:36
msgid ""
"\n"
"    SELinux denied access requested by $SOURCE. $TARGET_PATH may\n"
"    be a mislabeled. sshd is allowed to read content in /root/.ssh directory "
"if it\n"
"    is labeled correctly.\n"
"    "
msgstr ""

#: ../src/sshd_root.py:54
msgid "Restore Context"
msgstr "コンテキストの復元"

#: ../src/swapfile.py:27
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH \"$ACCESS\" to $TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への $SOURCE_PATH による \"$ACCESS\" を阻止しています。\n"
"    "

#: ../src/swapfile.py:31
msgid ""
"\n"
"    SELinux denied $SOURCE access to $TARGET_PATH.\n"
"    If this is a swapfile it has to have a file context label of\n"
"    swapfile_t. If you did not intend to use\n"
"    $TARGET_PATH as a swapfile it probably indicates a bug, however it could "
"also\n"
"    signal a intrusion attempt.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への $SOURCE のアクセスを拒否しました。\n"
"     これがスワップファイルならば、swapfile_t のファイルコンテキストラベルを \n"
"    持っている必要があります。$TARGET_PATH をスワップファイルとして \n"
"    使用する意図でなかった場合は、これは多分バグか、又は不正侵入の 試みの \n"
"    形跡の可能性があります。\n"
"     "

#: ../src/swapfile.py:39
msgid ""
"\n"
"    You can alter the file context by executing chcon -t swapfile_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"swapfile_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"    chcon -t swapfile_t '$TARGET_PATH' を実行すると、ファイルコンテキストを 変更することができます。\n"
"    また、完全な再ラベルの後でもそれらを保持するために、システム上でデフォルトの "
"ファイルコンテキストファイルも変更しなければなりません。\"semanage fcontext -a -t swapfile_t "
"'$FIX_TARGET_PATH'\"\n"
"    "

#: ../src/sys_module.py:28
msgid ""
"you do not believe your $SOURCE_PATH should be modifying the kernel, by "
"loading kernel modules"
msgstr "$SOURCE_PATH は kernel module をロードし、kernel を編集すべきではありません。"

#: ../src/sys_module.py:29
msgid "You might have been hacked."
msgstr "あなたはハッキングされているかもしれません。"

#: ../src/sys_module.py:33
msgid ""
"\n"
"    Your system may be seriously compromised! $SOURCE_PATH tried to load a "
"kernel module.\n"
"    "
msgstr ""
"\n"
"    ご使用のシステムには深刻な侵害の可能性があります! $SOURCE_PATH がカーネルモジュールをロードしようとしました。\n"
"    "

#: ../src/sys_module.py:37
msgid ""
"\n"
"    SELinux has prevented $SOURCE from loading a kernel module.\n"
"    All confined programs that need to load kernel modules should have "
"already had policy\n"
"    written for them. If a compromised application\n"
"    tries to modify the kernel this AVC will be generated. This is a serious\n"
"    issue. Your system may very well be compromised.\n"
"    "
msgstr ""

#: ../src/sys_module.py:46
msgid ""
"you do not believe that $SOURCE_PATH should be attempting to modify the "
"kernel by loading a kernel module."
msgstr "$SOURCE_PATH は kernel module をロードし、kernel を編集しようとすべきではありません。"

#: ../src/sys_module.py:47
msgid "A process might be attempting to hack into your system."
msgstr "あるプロセスがあなたのシステムへハッキングしようとしているかもしれません。"

#: ../src/sys_resource.py:28
msgid ""
"\n"
"    SELinux is preventing $SOURCE_PATH the \"sys_resource\" capability.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:32
msgid ""
"\n"
"    Confined domains should not require \"sys_resource\". This usually means "
"that     your system is running out some system resource like disk space, "
"memory, quota etc. Please clear up the disk and this\n"
"    AVC message should go away. If this AVC continues after you clear up the "
"disk space, please report this as a bug.\n"
"    "
msgstr ""

#: ../src/sys_resource.py:39
msgid ""
"you do not want processes to require capabilities to use up all the system "
"resources on your system;"
msgstr "プロセスにシステム上の全システムリソースを消費できる機能を要求させたくない場合;"

#: ../src/sys_resource.py:40
msgid ""
"you need to diagnose why your system is running out of system resources and "
"fix the problem.\n"
"\n"
"According to /usr/include/linux/capability.h, sys_resource is required to:\n"
"\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
"/* Override resource limits. Set resource limits. */\n"
"/* Override quota limits. */\n"
"/* Override reserved space on ext2 filesystem */\n"
"/* Modify data journaling mode on ext3 filesystem (uses journaling\n"
"   resources) */\n"
"/* NOTE: ext2 honors fsuid when checking for resource overrides, so\n"
"   you can override using fsuid too */\n"
"/* Override size restrictions on IPC message queues */\n"
"/* Allow more than 64hz interrupts from the real-time clock */\n"
"/* Override max number of consoles on console allocation */\n"
"/* Override max number of keymaps */\n"
msgstr ""

#: ../src/vbetool.py:30
msgid ""
"\n"
"    SELinux has prevented vbetool from performing an unsafe memory operation."
"\n"
"    "
msgstr "\n"
"    SELinux は vbetool による安全でないメモリー操作を阻止 しました\n"
"    "

#: ../src/vbetool.py:34
msgid ""
"\n"
"SELinux denied an operation requested by $SOURCE, a program used\n"
"to alter video hardware state.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as vbetool.  This tool is used to\n"
"reset video state when a machine resumes from a suspend.  If your machine\n"
"is not resuming properly your only choice is to allow this\n"
"operation and reduce your system security against such malware.\n"
"\n"
"    "
msgstr ""

#: ../src/vbetool.py:45 ../src/wine.py:56
msgid ""
"\n"
"If you decide to continue to run the program in question you will need\n"
"to allow this operation.  This can be done on the command line by\n"
"executing:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"
msgstr ""
"\n"
"問題になっているプログラムを継続して実行する決定をした場合は、この \n"
"操作を許可する必要があります。これは以下のようにコマンドラインで \n"
"実行できます:\n"
"\n"
"# setsebool -P mmap_low_allowed 1\n"

#: ../src/vbetool.py:55
msgid ""
"you want to ignore this AVC because it is dangerous and your machine seems "
"to be working correctly."
msgstr "このAVCを無効にしたい。このAVCは警告だが、マシンは正常に動作しているため。"

#: ../src/vbetool.py:56
msgid ""
"you must tell SELinux about this by enabling the vbetool_mmap_zero_ignore "
"boolean."
msgstr ""
"これについては、SELinux に vbetool_mmap_zero_ignore boolean を有効にする設定をしなければいけません。"

#: ../src/vbetool.py:62 ../src/wine.py:73
msgid "Turn off memory protection"
msgstr "メモリーの保護をオフにします"

#: ../src/wine.py:31
msgid ""
"\n"
"    SELinux has prevented wine from performing an unsafe memory operation.\n"
"    "
msgstr "\n"
"    SELinux は wine による安全でないメモリー操作の実行を阻止しました。\n"
"    "

#: ../src/wine.py:35
msgid ""
"\n"
"SELinux denied an operation requested by wine-preloader, a program used\n"
"to run Windows applications under Linux.  This program is known to use\n"
"an unsafe operation on system memory but so are a number of\n"
"malware/exploit programs which masquerade as wine.  If you were\n"
"attempting to run a Windows program your only choices are to allow this\n"
"operation and reduce your system security against such malware or to\n"
"refrain from running Windows applications under Linux.  If you were not\n"
"attempting to run a Windows application this indicates you are likely\n"
"being attacked by some for of malware or program trying to exploit your\n"
"system for nefarious purposes.\n"
"\n"
"Please refer to\n"
"\n"
"http://wiki.winehq.org/PreloaderPageZeroProblem\n"
"\n"
"Which outlines the other problems wine encounters due to its unsafe use\n"
"of memory and solutions to those problems.\n"
"\n"
"    "
msgstr ""

#: ../src/wine.py:66
msgid ""
"you want to ignore this AVC because it is dangerous and your wine "
"applications are working correctly."
msgstr "この AVC を無効にしたい。この AVC は警告だが、wine アプリケーションは正常に動作しているため。"

#: ../src/wine.py:67
msgid ""
"you must tell SELinux about this by enabling the wine_mmap_zero_ignore "
"boolean."
msgstr "これについては、SELinux に wine_mmap_zero_ignore を有効にする設定をしなければいけません。"

#: ../src/xen_image.py:27
msgid ""
"\n"
"    SELinux is preventing xen ($SOURCE_PATH) \"$ACCESS\" access to "
"$TARGET_PATH.\n"
"    "
msgstr ""
"\n"
"    SELinux は $TARGET_PATH への xen ($SOURCE_PATH) による  \"$ACCESS\" "
"アクセスを阻止しています。\n"
"    "

#: ../src/xen_image.py:31
msgid ""
"\n"
"    SELinux denied xen access to $TARGET_PATH.\n"
"    If this is a XEN image, it has to have a file context label of\n"
"    xen_image_t. The system is setup to label image files in directory /var/"
"lib/xen/images\n"
"    correctly.  We recommend that you copy your image file to /var/lib/xen/"
"images.\n"
"    If you really want to have your xen image files in the current "
"directory, you can relabel $TARGET_PATH to be xen_image_t using chcon.  You "
"also need to execute semanage fcontext -a -t xen_image_t '$FIX_TARGET_PATH' "
"to add this\n"
"    new path to the system defaults. If you did not intend to use "
"$TARGET_PATH as a xen\n"
"    image it could indicate either a bug or an intrusion attempt.\n"
"    "
msgstr ""
"\n"
"SELinux により $TARGET_PATH への xen のアクセスが拒否されました。\n"
"これが XEN イメージの場合は、 xen_image_t のファイルコンテキストラベルを持たせる\n"
"必要があります。 システムは /var/lib/xen/images ディレクトリ内でイメージファイル\n"
"にラベル付けを行なうよう正しく設定されています。 使用するイメージファイルを \n"
"/var/lib/xen/images ディレクトリにコピーすることをお勧めします。 どうしても xen イメージ\n"
"ファイルを現在のディレクトリに配置する必要がある場合は、 chcon  を使用して \n"
"$TARGET_PATH に xen_image_t のラベルを付け直してください。 \n"
"また、 semanage fcontext -a -t xen_image_t '$FIX_TATGET_PATH' を実行して、 この新しい\n"
"パスをシステムのデフォルト設定に追加する必要があります。 $TARGET_PATH を xen イメージ\n"
"として使用する意図がなかった場合は、 バグまたは不正侵入の試行を示している可能性があります。"

#: ../src/xen_image.py:41
msgid ""
"\n"
"    You can alter the file context by executing chcon -t xen_image_t "
"'$TARGET_PATH'\n"
"    You must also change the default file context files on the system in "
"order to preserve them even on a full relabel.  \"semanage fcontext -a -t "
"xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
msgstr ""
"\n"
"   chcon -t xen_image_t '$TARGET_PATH' を実行すると、ファイルコンテキストの 変更ができます。\n"
"    "
"また、完全な再ラベルの後でもそれらが保持できるようにシステム上でデフォルトのファイルコンテキストファイルの変更もしなければなりません。\"semanage "
"fcontext -a -t xen_image_t '$FIX_TARGET_PATH'\"\n"
"    "
